# -*- coding: utf-8 -*-
"""titanic-streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/thanhvietnguyen/Titanic-ML-project/blob/master/app/ui/titanic-streamlit.ipynb
"""

pip install streamlit

import streamlit as st
import requests

st.title("Titanic Survival Prediction")
st.write("Nhập thông tin hành khách và nhận dự đoán liệu họ có sống sót hay không.")

# ===== Nhập dữ liệu từ người dùng =====
sex = st.selectbox("Giới tính", ["male", "female"])
pclass = st.selectbox("Hạng vé (Pclass)", [1, 2, 3])
age = st.slider("Tuổi", min_value=0, max_value=100, value=30)
sibsp = st.number_input("Số anh chị em/vợ chồng đi cùng (SibSp)", min_value=0, max_value=10, value=0)
parch = st.number_input("Số cha mẹ/con đi cùng (Parch)", min_value=0, max_value=10, value=0)
fare = st.number_input("Giá vé (Fare)", min_value=0.0, value=30.0)
embarked = st.selectbox("Nơi lên tàu (Embarked)", ["C", "Q", "S"])

# ===== Gửi yêu cầu đến FastAPI =====
if st.button("Dự đoán"):
    input_data = {
        "Pclass": pclass,
        "Sex": sex,
        "Age": age,
        "SibSp": sibsp,
        "Parch": parch,
        "Fare": fare,
        "Embarked": embarked
    }

    try:
        response = requests.post("https://titanic-fastapi.onrender.com", json=input_data)
        result = response.json()

        if result["prediction"] == 1:
            st.success(f"Hành khách **có khả năng sống sót**, xác suất: {result['probability_survival']:.2%}")
        else:
            st.error(f"Hành khách **khó sống sót**, xác suất sống: {result['probability_survival']:.2%}")

    except Exception as e:
        st.error(f"Lỗi khi gọi API: {e}")