# -*- coding: utf-8 -*-
"""titanic-streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/thanhvietnguyen/Titanic-ML-project/blob/master/app/ui/titanic-streamlit.ipynb
"""

#pip install streamlit

import streamlit as st
import requests

st.title("Dự đoán sống sót Titanic")
st.write("Nhập thông tin hành khách và nhận dự đoán liệu họ có sống sót hay không.")

API_URL = "https://titanic-fastapi.onrender.com/predict"

# ===== Nhập dữ liệu từ người dùng =====
sex = st.selectbox("Giới tính", ["male", "female"])
pclass = st.selectbox("Hạng vé (Pclass)", [1, 2, 3])
age = st.slider("Tuổi", min_value=0, max_value=100, value=30)
sibsp = st.number_input("Số anh chị em/vợ chồng đi cùng (SibSp)", min_value=0, max_value=10, value=0)
parch = st.number_input("Số cha mẹ/con đi cùng (Parch)", min_value=0, max_value=10, value=0)
fare = st.number_input("Giá vé (Fare)", min_value=0.0, value=30.0)
embarked = st.selectbox("Nơi lên tàu (Embarked)", ["C", "Q", "S"])

# ===== Gửi yêu cầu đến FastAPI =====
if st.button("Dự đoán"):
    input_data = {
        "Pclass": pclass,
        "Sex": sex,
        "Age": age,
        "SibSp": sibsp,
        "Parch": parch,
        "Fare": fare,
        "Embarked": embarked
    }

    try:
        response = requests.post(API_URL, json=input_data)

        st.write("Status code:", response.status_code)
        st.write("Raw response:", response.text)

        if response.status_code == 200:
            result = response.json()

            if "error" in result:
                st.error(result["error"])
            else:
                label = "Sống sót" if result["prediction"] == 1 else "Không sống sót"
                st.success(f"Dự đoán: {label}")
                st.info(f"Xác suất sống: {result['probability_survival'] * 100:.2f}%")
        else:
            st.error("Lỗi từ API: " + response.text)

    except Exception as e:
        st.error(f"Lỗi khi gọi API: {e}")